#!/bin/sh
# File generated by ocamlbuild

cd '/Users/elbywan/Programmation/Année 2010 2011/ted'

rm -f translated/ABR.cmi
rm -f translated/ABR.cmx
rm -f translated/ABR.o
rm -f translated/Lists.cmi
rm -f translated/Lists.cmx
rm -f translated/Lists.o
rm -f translated/Matrices.cmi
rm -f translated/Matrices.cmx
rm -f translated/Matrices.o
rm -f translated/Monads.cmi
rm -f translated/Monads.cmx
rm -f translated/Monads.o
rm -f translated/QuickSort.cmi
rm -f translated/QuickSort.cmx
rm -f translated/QuickSort.o
rm -f translated/list.cmi
rm -f translated/list.cmx
rm -f translated/list.o
rm -f translated/ocaml_trad_tests.cmi
rm -f translated/ocaml_trad_tests.cmx
rm -f translated/ocaml_trad_tests.o
# Also clean the script itself
rm -f _build/sanitize.sh
